-- 코드를 입력하세요
SELECT  AO.ANIMAL_ID ANIMAL_ID,
        AO.NAME NAME
        FROM ANIMAL_INS A
        RIGHT OUTER JOIN (ANIMAL_OUTS) AO
        ON (AO.ANIMAL_ID = A.ANIMAL_ID)
        WHERE A.ANIMAL_ID IS NULL
        ORDER BY AO.ANIMAL_ID