-- 코드를 입력하세요
SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    WHERE TO_CHAR(DATETIME, 'HH24') >= 9 AND TO_CHAR(DATETIME, 'HH24') <= 19
    GROUP BY TO_CHAR(DATETIME, 'HH24')
    ORDER BY HOUR ASC