SELECT D.HOUR, NVL(A.COUNT, 0) COUNT
    FROM (
        SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR,
        COUNT(*) COUNT
        FROM ANIMAL_OUTS
        GROUP BY TO_CHAR(DATETIME, 'HH24')
    ) A
    RIGHT OUTER JOIN (
        SELECT LEVEL-1 HOUR
        FROM DUAL
        CONNECT BY LEVEL<=24
    ) D
    ON A.HOUR = D.HOUR
    ORDER BY D.HOUR